### ISSUE TITLE
[EPIC] HTTP Order API

### ISSUE THREAD

**Issue by leinlawun** [fincubator/booker#22]
- [x] Define HTTP Order API handlers (#18).
- [x] Implement HTTP Order API (#21).
- [x] Mock HTTP Order API (#19).
- [x] Write tests for HTTP Order API (#20).
